### ISSUE TITLE
Next and Previous buttons a bit confusing to user

### ISSUE THREAD

**Issue by AryanJ-NYC** [unixcommerce/clwd#1]
The next and prev buttons seem to go to the _next_ or _previous_ city. This won't be useful often and only leads to confusion.

**Comment by unixcommerce** [comment]
How could I fix this

**Comment by AryanJ-NYC** [comment]
Are the buttons necessary?

**Comment by unixcommerce** [comment]
Do you understand the purpose of the tool?

**Comment by AryanJ-NYC** [comment]
Two years later, nope. I don't.
