### ISSUE TITLE
Add post dates to posts

### ISSUE THREAD

**Issue by AryanJ-NYC** [unixcommerce/clwd#2]
Post dates would be helpful for users.

**Comment by unixcommerce** [comment]
Got it. I will add today

**Comment by unixcommerce** [comment]
How would you add it

**Comment by AryanJ-NYC** [comment]
Don't you guys have "10+ years of experience?"

**Comment by unixcommerce** [comment]
Yes

**Comment by unixcommerce** [comment]
Just to busy to do it

**Comment by unixcommerce** [comment]
If you need me to add it, just contact us on our website.
